name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and generate report
        run: |
          pytest --html=report.html --self-contained-html

      - name: Upload test report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.html

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload code as artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
